### ISSUE TITLE
Deleted package detected


### ISSUE THREAD

**Issue by ashishbijlani** [pilgrimtabby/manage-savestates#1]
I'm a Cyber Security researcher and developer of PackjGuard [1] to address open-source software supply chain attacks.

# Issue

During my research, I detected a _deleted package_ in this repository.

# Details

Specifically, the package `manage-savestates` mentioned in file `README` at line 56 does not exist on the public **PyPI** registry. A bad actor can hijack this package to propagate malicious code.

# Impact

Not only your apps/services using `https://github.com/pilgrimtabby/manage-savestates` repo code are vulnerable to this attack, but the users of your open-source Github repo could also fall victim.

You could read more about such attacks here: https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610

# Remediation
         
Please highlight this in file README and register a placeholder package for `manage-savestates` on public PyPI soon to remediate.

To automatically fix such issues in future, please install PackjGuard Github app [1].
                                         
Thanks!    

1. PackjGuard is a Github app that monitors your repos 24x7, detects vulnerable/malicious/risky open-source dependencies, and creates pull requests for auto remediation: https://github.com/marketplace/packjguard

**Comment by pilgrimtabby** [comment]
Hello, thanks for opening an issue. I'm not sure what you mean, though: manage-savestates is on the public PyPi registry (link: https://pypi.org/project/manage-savestates/).

**Comment by ashishbijlani** [comment]
Yes, looks like you registered a new version. Closing this issue. Sorry about the confusion. Thanks!
